{{- if and (not .Values.n8n.apiKey.existingSecret) .Values.n8n.apiKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n-resource-operator.apiKeySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-resource-operator.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.n8n.apiKey.secretKey }}: {{ .Values.n8n.apiKey.value | b64enc | quote }}
{{- end }}
